create database hns_db;
use hns_db;
create table USER (
	USER_ID int not null,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    GENDER VARCHAR(10),
    AGE INT,
    PRIMARY KEY(USER_ID)
) DEFAULT CHARSET=UTF8;

CREATE TABLE CONTENT (
	CONTENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CONTENT_TYPE VARCHAR(10) NOT NULL,
    CONTENT_SRC VARCHAR(100) NOT NULL,
    primary key(CONTENT_ID),
    foreign key(USER_ID) references USER(USER_ID) ON DELETE CASCADE

) DEFAULT CHARSET=UTF8;

CREATE TABLE BOARDER (
	BOARDER_ID INT NOT NULL,
    CONTENT_ID INT NOT NULL,
    VIEW_CNT INT NOT NULL,
    BOARDER_TITLE varchar(100) NOT NULL,
    BOARDER_DESCRIPTION text NOT NULL,
    primary key(BOARDER_ID),
    foreign key(CONTENT_ID) references CONTENT(CONTENT_ID) ON DELETE CASCADE
) DEFAULT CHARSET=UTF8;